version: "3.3"
services:
 mysql:
  image: mysql:8
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: 1
   MYSQL_DATABASE: app
   MYSQL_USER: app
   MYSQL_PASSWORD: pass
  ports:
   - "3306:3306"

  volumes:
   - ./schema:/docker-entrypoint-initdb.d